services:
  dvm:
    container_name: neo4j_dvm
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/12345678
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: bdms
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./bdms-backup:/backup/bdms-backup
